name: 'Linting & test'

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # githubs own action plugin - a way Github knows to get all your code from github, and run actions on it - S in actions
      - name: 'Install dependencies'
        run: npm install
      - name: 'Run linting'
        run: npm run lint
  E2E-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install dependencies'
        run: npm install
      - uses: cypress-io/github-action@v4 # Cypress way to run you e2e test - cypress plugin that automaticly runs your cypress-e2e test - NO S IN ACTION!
        with:
          start: npm run dev
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install dependencies'
        run: npm install
      - name: 'Run unit tests'
        run: npm run test:unit
